// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    // Documentos raíz / Root docs
    'overview',            // Visión general (Overview)
    'opening',             // Apertura (Opening)

    // Categoría: Panel de Elementos / Elements panel
    {
      type: 'category',
      label: 'Panel de Elementos (Elements)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Elementos',
        description: 'Guía completa de cada apartado del Elements Panel: DOM, CSS, Box Model, pseudoelementos…',
        slug: 'elements'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'elements'
        }
      ],
    },
    



    // Categoría: Consola / Console
    {
      type: 'category',
      label: 'Consola (Console)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Consola',
        description: 'Guía completa de la Consola de DevTools: ejecutar JavaScript, usar la API de console, filtrar logs, medir tiempos y depurar errores',
        slug: 'console'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'console'   // Carpeta docs/console/
        }
      ],
    },

    // Categoría: Fuentes / Sources
    {
      type: 'category',
      label: 'Fuentes (Sources)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Fuentes (Sources)',
        description: 'Explora cómo depurar JavaScript, establecer puntos de interrupción y editar archivos en vivo dentro del panel Sources de DevTools.',
        slug: 'sources'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'sources'   // Carpeta docs/sources/
        }
      ],
    },

    // Categoría: Red / Network
    {
      type: 'category',
      label: 'Red (Network)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Red',
        description: 'Guía completa para monitorizar y depurar tráfico de red: peticiones, filtros, encabezados y simulación',
        slug: 'network'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'network'   // Carpeta docs/network/
        }
      ],
    },

    // Categoría: Rendimiento / Performance
    {
      type: 'category',
      label: 'Rendimiento (Performance)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Rendimiento',
        description: 'Aprende a usar el panel Performance de DevTools para registrar, analizar y optimizar el rendimiento de tu sitio web: timeline, FPS, throttling y más.',
        slug: 'performance'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'performance' // Carpeta docs/performance/
        }
      ],
    },
    // Categoría: Memoria / Memory
    {
      type: 'category',
      label: 'Memoria (Memory)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Panel de Memoria',
        description: 'Aprende a analizar y depurar el uso de memoria en tu aplicación web usando el panel Memory de DevTools: snapshots, árboles retenidos, instrumentación de asignación y recolección de basura.',
        slug: 'memory'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'memory' // Carpeta docs/memory/
        }
      ],
    },

    // Categoría: Aplicación / Application
    {
      type: 'category',
      label: 'Aplicación (Application)',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Guía de Aplicación',
        description: 'Guía completa sobre el manejo y almacenamiento de datos en aplicaciones web, optimización de recursos y uso de DevTools.',
        slug: 'application'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'application' // Carpeta docs/Aplicacion/
        }
      ],
    },
    

    // Categoría: Seguridad / Security
    {
      type: 'category',
      label: 'Seguridad (Security)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'security'   // Carpeta docs/security/
        }
      ],
    },

    // Categoría: Lighthouse / Lighthouse
    {
      type: 'category',
      label: 'Lighthouse (Lighthouse)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'lighthouse' // Carpeta docs/lighthouse/
        }
      ],
    },

    // Sección de anexos o referenciales / Appendices & References
    {
      type: 'category',
      label: 'Apéndices y Referencias (Appendices & References)',
      collapsed: true,
      items: [
        'glossary',           // Glosario (Glossary)
        'shortcuts',          // Atajos (Shortcuts)
        'faq',                // Preguntas frecuentes (FAQ)
      ],
    },
  ],
};

export default sidebars;
