// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    // Documentos raíz / Root docs
    'overview',            // Visión general (Overview)
    'opening',             // Apertura (Opening)

    // Categoría: Panel de Elementos / Elements panel
    {
      type: 'category',
      label: 'Panel de Elementos (Elements)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'elements'  // Carpeta docs/elements/
        }
      ],
    },

    // Categoría: Consola / Console
    {
      type: 'category',
      label: 'Consola (Console)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'console'   // Carpeta docs/console/
        }
      ],
    },

    // Categoría: Fuentes / Sources
    {
      type: 'category',
      label: 'Fuentes (Sources)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sources'   // Carpeta docs/sources/
        }
      ],
    },

    // Categoría: Red / Network
    {
      type: 'category',
      label: 'Red (Network)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'network'   // Carpeta docs/network/
        }
      ],
    },

    // Categoría: Rendimiento / Performance
    {
      type: 'category',
      label: 'Rendimiento (Performance)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'performance'// Carpeta docs/performance/
        }
      ],
    },

    // Categoría: Memoria / Memory
    {
      type: 'category',
      label: 'Memoria (Memory)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'memory'     // Carpeta docs/memory/
        }
      ],
    },

    // Categoría: Aplicación / Application
    {
      type: 'category',
      label: 'Aplicación (Application)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'application'// Carpeta docs/application/
        }
      ],
    },

    // Categoría: Seguridad / Security
    {
      type: 'category',
      label: 'Seguridad (Security)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'security'   // Carpeta docs/security/
        }
      ],
    },

    // Categoría: Lighthouse / Lighthouse
    {
      type: 'category',
      label: 'Lighthouse (Lighthouse)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'lighthouse' // Carpeta docs/lighthouse/
        }
      ],
    },

    // Sección de anexos o referenciales / Appendices & References
    {
      type: 'category',
      label: 'Apéndices y Referencias (Appendices & References)',
      collapsed: true,
      items: [
        'glossary',           // Glosario (Glossary)
        'shortcuts',          // Atajos (Shortcuts)
        'faq',                // Preguntas frecuentes (FAQ)
      ],
    },
  ],
};

export default sidebars;
